voxpupuli/puppet-keepalived

manifests/init.pp
Enabling [parser=future](https://docs.puppetlabs.com/puppet/3/reference/experiments_future.html#enabling-the-future-parser) caused:
`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: This Array Expression is not productive. A Host Class Definition can not end with a non productive construct at /etc/puppet/modules/keepalived/manifests/init.pp:35:9 on node admin022
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`
=> fix where parser=future caused "This Array Expression is not productive"

manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb
Validate that the `priorty` param provided to `keepalived::vrrp::instance`
is semantically valid. This will catch errors early, before keepalived is
incorrectly configured.
The RFC states that the priority is an 8bit unsigned integer which means
that it must have a range of 0-255 inclusive. However it also goes on to say
that 0 and 255 are reserved for special operational use.
https://tools.ietf.org/html/rfc3768#section-5.3.4
Validate that the `virtual_router_id` param provided to
`keepalived::vrrp::instance` is semantically valid. This will catch errors
early, before keepalived is incorrectly configured.
The RFC states that the router ID must have a range of 1-255 inclusive.
https://tools.ietf.org/html/rfc3768#section-5.3.3
---
Plus reducing repetition in the tests for …
=> Validate keepalived::vrrp::instance priority and virtual_router_id params

lib/facter/keepalived_version.rb
Older versions of facter don't have the "which" method
=> Test for the 'which' method before using it

templates/vrrp_instance.erb
Scripts should be enclosed in " in order to receive arguments properly.
=> instance scripts syntax fixed

manifests/vrrp/instance.pp
Puppet 4 will not automatically cast strings to integers for the sake of comparison, so we can add 0 to each string to force a type casting before doing the comparison.
=> Type cast strings to integers for puppet 4

manifests/vrrp/instance.pp
Puppet 4 will not automatically cast strings to integers for the sake of comparison, so we can add 0 to each string to force a type casting before doing the comparison.
This is @danieldreier's; the change was removed from master for some reason.
=> Force type casting of strings to ints for puppet 4

manifests/vrrp/instance.pp
The $notify_script parameter is defined twice.
=> Remove duplicate class parameter

manifests/init.pp
rror 400 on SERVER: This Array Expression has no effect. A Host Class
Definition can not end with a value-producing expression without other
effect at keepalived/manifests/init.pp:35:9
=> future parser: removed Class[ 'keepalived' ]

manifests/config.pp
Keepalived currently only restarts if /etc/keepalived folder is created, which is on clean install. It does not restart if keepalived.conf is changed.
This PR proposes to do so by subscribing keepalived service resource to keepalived.conf concat instead of /etc/keepalived folder.
=> Keepalived should be restarted on Concat changes, not File

manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb
Hi,
we have machines with multiple interfaces. We have to set this options, since the machine has no primary ip on the second interface where the service ip binded.
=> Added mcast_src_ip option

manifests/lvs/virtual_server.pp
This PR is just the simplest fix for #75 mentioned by rotulet. It simply appends 'zzz' to the ordering for the closing bracket fragment to ensure the bracket is placed at the end of the block rather than the front.
Looks like the overall ordering works out as follows:
> 001 = config (header)
> 002 = vrrp/script
> 010 = global_defs
> 050 = vrrp/sync_group
> 100 = vrrp/instance
> 250 = lvs/real_server with 250-${virtual_server}-${_name}
> 250 = lvs/virtual_server with 250-${_name}-000
> 250 = lvs/virtual_server with 250-${_name} **<-- this is the problematic bracket**
> 999 = config (footer)
Appending 'zzz' seems a bit kludgy, but I believe it works while retaining the overall ordering that currently exists (with the bracket corrected). If you have a better approach I would be happy to do a …
=> simple ordering fix for #75

templates/vrrp_instance.erb
When upgrading from 1.2.4 to 1.2.5, the new version schedules a refresh because of a newline in templates/vrrp_instance.erb
This commit avoids having a refresh of the keepalived service with an existing configuration.
=> Avoid newline (and with this a refresh of service) for existing configs

.sync.yml, .travis.yml, metadata.json
=> Enable beaker tests and drop Debian 6 support

.sync.yml, .travis.yml, README.md, metadata.json
At Vox Pupuli, we stopped supporting Puppet 4 after it went EOL.
https://voxpupuli.org/blog/2019/01/03/dropping-puppet4/
Debian 7 is also EOL and Puppet Inc don't publish Puppet 6 packages for it.
=> Drop support for Puppet 3, Puppet 4 and Debian 7

manifests/init.pp, manifests/lvs/real_server.pp, manifests/lvs/virtual_server.pp, manifests/vrrp/instance.pp, manifests/vrrp/script.pp, spec/acceptance/class_spec.rb, spec/classes/keepalived_spec.rb, spec/defines/keepalived_lvs_real_server_spec.rb, spec/defines/keepalived_lvs_virtual_server_spec.rb, spec/defines/keepalived_vrrp_instance_spec.rb, types/options.pp
This is a breaking change as several parameters now only accept integers
instead of strings.
Fixes #159
=> Use data types instead of validate functions

manifests/config.pp
`create_resources` is best avoided since Puppet 4 onwards.
=> Replace `create_resources` with iteration

manifests/vrrp/script.pp, spec/defines/keepalived_vrrp_script_spec.rb
Reverts voxpupuli/puppet-keepalived#177
The example in the readme is
```puppet
keepalived::vrrp::script { 'check_nginx':
script => '/usr/bin/killall -0 nginx',
}
```
=> Revert "use Stdlib::Absolutepath datatype with vrrp script"

manifests/vrrp/track_process.pp, spec/defines/keepalived_vrrp_track_process_spec.rb, templates/vrrp_track_process.epp
This change the parameter fullcommand to full_command for keepalived::vrrp::track_process
Extracted from the manual page of keepalived.conf (2.0.14) : http://www.keepalived.org/manpage.html
```
vrrp_track_process <STRING> {
process <QUOTED_STRING>
weight <-254..254>
quorum NUM
delay SECS
full_command
}
```
Fixes #179
=> Change the fullcommand parameter to full_command for keepalived::vrrp::track_process

README.md, manifests/vrrp/instance.pp, manifests/vrrp/sync_group.pp, spec/defines/keepalived_vrrp_instance_spec.rb, spec/defines/keepalived_vrrp_sync_group_spec.rb, templates/vrrp_instance.erb, templates/vrrp_sync_group.erb
=> add support for native_ipv6 in vrrp instances

manifests/vrrp/instance.pp
Hi,
I was building keepalived cluster and I suffered a bit due to lack of metric support.
I've added this feature and I want to merge it with upstream.
=> Support for metric argument in vrrp_instancevirtual_routes

.sync.yml, .travis.yml, metadata.json, spec/acceptance/keepalived_spec.rb
I've been using this on RHEL 7 all year.
=> Add CentOS 7 to list of supported OSes

spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb
Virtual ip addresses should be setup on vrrp interface if use_vmac is set
=> virtual_ipaddress should be on vrrp interface if use_vmac is set

types/vrrp/instance/vrule.pp
Set curly Braces in Type-Definition as stated in Puppet-Documentation.
Puppet-Parser 4.10.12 complains with "Syntax error at '=>'", whereas
Puppet-Parser 6.2 and 6.4 don't...
However Puppet-Documentation states, that curly Braces have to be there.
=> Fix `Keepalived::Vrrp::Instance::VRule` syntax

manifests/init.pp
=> Use contain for sub classes in this module

README.md, manifests/vrrp/instance.pp, manifests/vrrp/unicast_peer.pp, spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb
This is a continuation of #133, with the tests passing. Because the new code enforces use of `Stdlib::IP::Address`, it no longer supports setting `unicast_source_ip` to arbitrary strings, so I had to change `_VALUE_` to an ip address in the tests. Other changes were inward-facing, reflecting the shift from a single concat fragment to many.
Fixes #133
=> Enable automatic unicast configuration with exported resources - pass tests

manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb
Considering the following 3-node-setup:
| *Node* | *IP* |
| --- | --- |
| node1 | 10.0.0.1 |
| node2 | 10.0.0.2 |
| node3 | 10.0.0.3 |
There are two different VIPs bound to two separate VRRP-instances
* instance1, VIP primarily held by _node1_
* instance2, VIP primarily held by _node2_.
Both instances share the same unicast-peers - like in below config-snippet from _node1_ (10.0.0.1).
```yaml
keepalived::vrrp_instance:
instance1:
unicast_peers:
- 10.0.0.2
- 10.0.0.3
instance2:
unicast_peers:
- 10.0.0.2
- 10.0.0.3
```
That was a working config before - but by introducing the `keepalived::vrrp::unicast_peer` type in #227 this now fails as duplicate `keepalived::vrrp::unicast_peer` resources would get created with the same resource-names.
Therefor I would like to suggest binding the …
=> make unicast-peer resource-name unique by adding the instance-name

manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
This PR allows the `enable_dbus` option from keepalived to be set via puppet/hiera.
=> Add enable_dbus option

templates/vrrp_instance.erb
Documentation says a string is allowed, but it hadn't worked due to a code bug.
The same change was applied to virtual_ipaddress earlier. (see d1f58fe2)
=> Allow virtual_ipaddress_excluded to be a string

README.md, manifests/init.pp, manifests/install.pp
I need the possibility to fix the version of keepalived, so, like service_manage, I introduce package_manage to install keepalived from another puppet module.
n/a
=> Add the possibility to manage the package outside the module

README.md, manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
I want to manage with this puppet module Keepalived process behaviour on my linux system:
* priority
* rt_prio
* no_swap
Ref: https://github.com/acassen/keepalived/blob/master/doc/man/man5/keepalived.conf.5.in
None
=> Keepalived processes behaviour are tunable via globaldefs: prio, rt_prio, no_swap

README.md, manifests/config.pp, manifests/init.pp, spec/acceptance/keepalived_spec.rb, templates/include-external-configs.epp
Some fragments of my keepalived setup are managed by an external tool. I want to be able to include them as verbatim using include directive.
=> Allow to include external keepalived config fragment

REFERENCE.md, manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
This pull request allows the vrrp_check_unicast_src option to be set in keepalived.conf.
Was unable to set vrrp_check_unicast_src option using the existing module code.
=> support for vrrp_check_unicast_src option

REFERENCE.md, manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb
The `use_vmac_addr` parameter tells keepalived to use virtual MAC addresses for virtual IPs.
The parameter `use_vmac` only affects VRRP packages.
=> add parameter use_vmac_addr to VRRP instance

REFERENCE.md, manifests/vrrp/track_process.pp, spec/defines/keepalived_vrrp_track_process_spec.rb, templates/vrrp_track_process.epp, types/vrrp/instance/vrule.pp
These seem to be available from keepalived 2.0.16 onwards. Which also changes purpose of the delay parameter to be the default for both.
=> Add `terminate_delay` and `fork_delay` parameters to `keepalived::vrrp::track_process`

manifests/vrrp/instance.pp, manifests/vrrp/unicast_peer.pp
Config fragments are called 100-$NAME-key (Note: parts are separated by dashes). Now if the following conditions are met, ordering will be messed up:
- $NAME contains dashes
- you're trying to set up more than one VRRP instance
- instance names contain unequal amounts of dashes
- one name is a substring of the other
I created another "ordersafe" variable that does not contain dashes. Also I noticed that $_name could still contain colons, slashes, ... because regsubst was just removing the first occurrence. The G flag will fix this, while we're here.
Fixes #302
=> Avoid messing up fragment ordering if instance name contains dashes

manifests/vrrp/instance.pp, templates/vrrp_instance.erb
As described in #304, collect_unicast_peers will add the local source IP to the list of unicast_peers. Currently this is a rather cosmetic problem, but it may confuse someone unfamiliar with the module who's looking at the configuration file.
Also, the ideal contents for unicast_src_ip which will match the rest of the configuration is determined by the module, but it is never explicitly added to it. Instead we're relying on Keepalived to come to the same result. I added it to the template (still overridable by setting unicast_source_ip explicitly) and moved it's fragment below "if $collect_unicast_peers" for this to work.
Fixes #304
=> Improve collect_unicast_peers

manifests/vrrp/script.pp, spec/defines/keepalived_vrrp_script_spec.rb, templates/vrrp_script.erb
Add support for the init_fail parameter to keepalived::vrrp::script
Fixes #257
=> Add support for the init_fail parameter to keepalived::vrrp::script

REFERENCE.md, manifests/lvs/real_server.pp, manifests/lvs/virtual_server.pp, manifests/vrrp/script.pp, manifests/vrrp/sync_group.pp
=> Replace all occurrences of illegal chars in the name var

REFERENCE.md, manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb
The Variant of `$track_script`'s Datatype
```
Variant[Array[String[1]],String[1]] $track_script
```
has to get handled correctly in the ERB-File.  Otherwise it fails with a single String.
fixes 4307d70f04396dc9d0316d0b52e0acc30c8b1ddf
=> vrrp_instance::track_script: Fix Datatype-Mismatch

spec/acceptance/keepalived_spec.rb
Use shared example for idempotency test
setup host with minimal working configuration
Fixes #324
=> Refactor acceptance test

REFERENCE.md, manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb
This is a followup of
https://github.com/voxpupuli/puppet-keepalived/pull/322 and https://github.com/voxpupuli/puppet-keepalived/pull/319
=> vrrp::instance::track_script: Enforce Array datatype 2

REFERENCE.md, data/os/Debian.yaml, data/os/Gentoo.yaml, data/os/RedHat.yaml, manifests/init.pp, spec/classes/keepalived_spec.rb
This is a followup of 86b83d3bb245d212a14afa8a4ae9bf31db50761d. We don't need to explicitly set hasrestart to false/true. All systems run systemd and the units have a working restart option so we can use it. And instead of hardcoding this we can just set it to undef so puppet figures this out on its own.
=> service: hasrestart/hasstatus: use Puppet defaults

README.md, REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/keepalived_spec.rb
allow hiera to define keepalived::global_defs
add global_defs parameter to init.pp
add class keepalived::global_defs if $keepalived::global_defs is defined
n/a
=> allow hiera to define keepalived::global_defs

manifests/vrrp/instance.pp, metadata.json, spec/defines/keepalived_vrrp_instance_spec.rb
To not reveal sensitive Data with the Variable `$auth_pass`, the rendered Template gets wrapped as Datatype `Sensitive`.
To not reveal sensitive Data with the Variable `$auth_pass`, the rendered Template gets wrapped as Datatype `Sensitive`.  
Fixes #338
=> Allow Sensitive `$auth_pass`

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/acceptance/keepalived_spec.rb, spec/classes/keepalived_spec.rb
I added a new overridable param called `config_validate_cmd`. It is used as input for the validate_cmd param of the keepalived.conf concat fragment. This should catch broken configs in the future.
Fixes #345
=> Add `validate_cmd` for `keepalived.conf`

REFERENCE.md, manifests/vrrp/track_process.pp, spec/defines/keepalived_vrrp_track_process_spec.rb, templates/vrrp_track_process.epp
With this, setting parameter to check for vrrp processes is possible.
=> allow setting process parameters for `track_process`

spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
The easier option would be to switch snmp_socket to undef by default, but that would be a breaking change.
=> snmp: Only configure snmp_socket when it is required

REFERENCE.md, manifests/init.pp
Optional doesn't make sense here because we cannot pass undef when the parameter has a default value. And the resources require an absolute path.
=> config_validate_cmd: Switch datatype to absolute path
