voxpupuli/puppet-keepalived

.fixtures.yml, lib/facter/keepalived_version.rb, metadata.json, spec/unit/facter/keepalived_version_spec.rb
Also fix some module install errors that got me
=> Adds keepalived_version fact

.gitignore, Gemfile, spec/acceptance/class_spec.rb, spec/acceptance/fact_spec.rb, spec/acceptance/nodesets/centos-59-x64.yml, spec/acceptance/nodesets/centos-65-x64.yml, spec/acceptance/nodesets/debian-70rc1-x64.yml, spec/acceptance/nodesets/debian-73-x64.yml, spec/acceptance/nodesets/default.yml, spec/acceptance/nodesets/ubuntu-server-10044-x64.yml, spec/acceptance/nodesets/ubuntu-server-12042-x64.yml, spec/acceptance/nodesets/ubuntu-server-1404-x64.yml, spec/spec_helper_acceptance.rb
Adds some basic acceptance tests using beaker
It's possible to spin up multiple nodes with beaker, so it could be possible in the future to test that the virtual IP stuff. But for now I'm just keeping it simple :+1:
=> Add acceptance tests

lib/facter/keepalived_version.rb, spec/unit/facter/keepalived_version_spec.rb
Regex switched up to catch multiple digits
=> Fixes issue with version fact

manifests/vrrp/script.pp, templates/vrrp_script.erb
=> implement use of weight_real in vrrp_script

manifests/config.pp, manifests/init.pp
Hi,
I want to add hiera support as we usually manage our data via Hiera.
Best,
Cem
=> Add hiera support

README.md, manifests/config.pp, manifests/init.pp
Add hiera support for `vrrp_instance` and `vrrp_sync_group` defines
=> Extend hiera support

manifests/vrrp/script.pp, spec/defines/keepalived_vrrp_script_spec.rb, templates/vrrp_script.erb
Keepalived version 1.3.0 added options to run vrrp_scripts under different user/groups.  This PR adds the functionality to the vrrp::script define.
=> * Allow user and group in vrrp::script

README.md
=> removes  trailing whitespace in README.md

CHANGELOG.md
Fix the `Unreleased` in the CHANGELOG
=> release 2.0.0

.sync.yml, spec/classes/keepalived_global_defs_spec.rb, spec/classes/keepalived_spec.rb, spec/defines/keepalived_lvs_real_server_spec.rb, spec/defines/keepalived_lvs_virtual_server_spec.rb, spec/defines/keepalived_vrrp_instance_spec.rb, spec/defines/keepalived_vrrp_script_spec.rb, spec/defines/keepalived_vrrp_sync_group_spec.rb, spec/spec_helper.rb, spec/unit/facter/keepalived_version_spec.rb
=> use rspec-puppet-facts

manifests/config.pp, manifests/global_defs.pp, manifests/install.pp, manifests/lvs/virtual_server.pp, manifests/params.pp, manifests/service.pp, manifests/vrrp/instance.pp, manifests/vrrp/script.pp
=> remote leading semicolomns

manifests/vrrp/script.pp, spec/defines/keepalived_vrrp_script_spec.rb
=> use Stdlib::Absolutepath datatype with vrrp script

manifests/lvs/virtual_server.pp, spec/defines/keepalived_lvs_virtual_server_spec.rb, templates/lvs_virtual_server.erb
add missing virtual_server option: quorum_up and quorum_down.
Tests have been corrected accordingly.
=> feat: add quorum_up and quorum_down in virtual_server

.msync.yml, .sync.yml, .travis.yml, Gemfile, Rakefile, spec/spec_helper.rb
=> modulesync 2.7.0 and drop puppet 4

.sync.yml, .travis.yml, metadata.json
=> Add Ubuntu 16 and 18 to list of supported OSes

.github/CONTRIBUTING.md, .msync.yml, .travis.yml, Gemfile, manifests/lvs/real_server.pp, manifests/vrrp/sync_group.pp, manifests/vrrp/track_process.pp, spec/spec_helper.rb
=> modulesync 2.8.0

README.md, manifests/config.pp, manifests/init.pp
Adds option to configure LVS real and virtual servers from hiera level
Fixes #116 ?
=> LVS hiera support

manifests/lvs/virtual_server.pp, templates/lvs_virtual_server.erb
=> Add support for sh-port and sh-fallback flags to lvs virtual servers

README.md, manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb, types/vrrp/instance/vrule.pp
This PR adds support for keepaliveds virtual_rules
n/a
=> add support for virtual_rules

.github/CONTRIBUTING.md, .travis.yml, Gemfile, Rakefile, manifests/params.pp, spec/spec_helper.rb
=> modulesync 2.9.0

.github/CONTRIBUTING.md, .msync.yml, .rubocop.yml, Gemfile, Rakefile, manifests/params.pp, spec/spec_helper.rb
=> modulesync 2.12.0

manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
Fixes https://github.com/voxpupuli/puppet-keepalived/issues/205
- All spec tests pass.
- Beaker tests do provide the expected keepalived config file.
=> add vrrp_garp_master_refresh / vrrp_garp_lower_prio_delay params

spec/acceptance/keepalived_spec.rb
=> add acceptance tests about global_defs

.github/SECURITY.md, .msync.yml, .rubocop.yml, .travis.yml, Gemfile, manifests/global_defs.pp, manifests/init.pp, manifests/install.pp, manifests/lvs/virtual_server.pp, manifests/service.pp, manifests/vrrp/instance.pp, manifests/vrrp/script.pp, manifests/vrrp/sync_group.pp, manifests/vrrp/track_process.pp, spec/spec_helper_acceptance.rb
=> modulesync 3.0.0 & puppet-lint updates

manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
Add the ability to configure `enable_snmp_vrrp` which was missing from this puppet module.
=> Add enable_snmp_vrrp option

types/vrrp/instance/vrule.pp
puppet-lint flagged these lines
=> Resolve puppet-lint notices

metadata.json
=> puppetlabs/concat: Allow 7.x / puppetlabs/stdlib: Allow 7.x

metadata.json
=> Drop Debian 8 support

metadata.json
=> Enable Debian 9 support

metadata.json
=> Drop Puppet 5 support; add Puppet 7 support

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .msync.yml, Dockerfile, Gemfile, spec/defines/keepalived_vrrp_instance_spec.rb
=> modulesync 4.1.0

manifests/vrrp/instance.pp, spec/defines/keepalived_vrrp_instance_spec.rb, templates/vrrp_instance.erb
=> Use Puppet-Datatype Sensitive for $auth_pass

manifests/global_defs.pp
This PR fixes incorrect documentation of some puppet resource keys.
=> Fix incorrect documentation

templates/vrrp_instance.erb
Unused sections should not generate additional newlines,
=> vrrp_instance template: Remove forced newlines

metadata.json, spec/acceptance/keepalived_spec.rb
Bumps Debian dependency versions.
n/a
=> Add Debian 10/11 and Ubuntu 20.04 support

manifests/vrrp/sync_group.pp, spec/defines/keepalived_vrrp_sync_group_spec.rb, templates/vrrp_sync_group.erb
Adds support for track_scripts inside vrrp_sync_groups
Closes #228
=> Add track vrrp scripts to vrrp_sync_groups

manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
Manage with this puppet modules if defined
* vrrp_garp_master_delay
* vrrp_garp_master_refresh
* vrrp_garp_master_refresh_delay
=> Add vrrp_garp_master_{delay, refresh, refresh_repeat} tunables in globaldefs

REFERENCE.md, manifests/lvs/virtual_server.pp, templates/lvs_virtual_server.erb
Signed-off-by: Arthur Outhenin-Chalandre <arthur.outhenin-chalandre@cern.ch>
Add support for mh lb_algo, also add related mh_port and mh_fallback similarly to sh_port and sh_fallback.
=> Add support for mh lb_algo

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, .puppet-lint.rc, .sync.yml, Dockerfile, Gemfile, Rakefile, lib/facter/keepalived_version.rb, manifests/config.pp, manifests/init.pp, spec/acceptance/keepalived_spec.rb, spec/classes/keepalived_global_defs_spec.rb, spec/classes/keepalived_spec.rb, spec/defines/keepalived_lvs_real_server_spec.rb, spec/defines/keepalived_lvs_virtual_server_spec.rb, spec/defines/keepalived_vrrp_instance_spec.rb, spec/defines/keepalived_vrrp_script_spec.rb, spec/defines/keepalived_vrrp_sync_group_spec.rb, spec/defines/keepalived_vrrp_track_process_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb, spec/unit/facter/keepalived_version_spec.rb
=> modulesync 5.2.0

README.md, manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
Add vrrp_version and max_auto_priority tunable support
None
=> vrrp_version and max_auto_priority global parameters

manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
**Pull Request (PR) description**
Add support for the dynamic_interfaces option in the global_defs section.
This is similar to pull-request #219 , but with tests.
**This Pull Request (PR) fixes the following issues**
None
=> Add support for dynamic_interfaces in global_defs section

README.md, manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
Add support of vrrp_notify_fifo and vrrp_notify_fifo_script
=> Add support of vrrp_notify_fifo*

.github/CONTRIBUTING.md, .msync.yml, Gemfile
=> modulesync 5.3.0

spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
Address bug I introduce in previous PR. Keep one line, one option in keepalived config.
=> fix template rendering with vrrp_priority and vrrp_fifo_* options

manifests/vrrp/instance.pp, manifests/vrrp/track_file.pp, spec/defines/keepalived_vrrp_track_file_spec.rb, templates/vrrp_instance.erb, templates/vrrp_track_file.epp
This PR adds the option to set and manage a vrrp track file
=> add option to set a vrrp track file

REFERENCE.md, manifests/global_defs.pp, spec/classes/keepalived_global_defs_spec.rb, templates/globaldefs.erb
This adds the option `vrrp_min_garp` to the global options.
=> add global option vrrp_min_garp

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 3.5.0

manifests/vrrp/sync_group.pp, spec/defines/keepalived_vrrp_sync_group_spec.rb, templates/vrrp_sync_group.erb
**Pull Request (PR) description**
Add support for the track_interface option of a vrrp sync group.
**This Pull Request (PR) fixes the following issues**
None
=> Add support for track_interface option to vrrp_sync_group

metadata.json
=> Drop EoL Ubuntu 16.04 & 18.04 support

metadata.json
=> puppetlabs/concat: Allow 8.x & 9.x

metadata.json
=> Add EL8 support

REFERENCE.md, manifests/vrrp/instance.pp, templates/vrrp_instance.erb
we should wait with merging until the next major release.
=> vrrp::instance: virtual_rules: Enforce Array datatype

REFERENCE.md, manifests/vrrp/instance.pp, templates/vrrp_instance.erb
we should keep this open until the next major release
=> vrrp::instance: track_interface: Enforce Array datatype

REFERENCE.md, manifests/vrrp/instance.pp
we should keep this open until the next major release.
=> vrrp::instance: track_script: Enforce Array datatype

metadata.json
=> Add OracleLinux Support

metadata.json
=> Add AlmaLinux support

metadata.json
=> Add Rocky Support
